/* Deploy compiled Truffle artifacts with the locally configured Sepolia key. */
const fs = require("fs");
const path = require("path");
require("dotenv").config({ path: path.resolve(__dirname, "../../../.env") });
const { Contract, ContractFactory, JsonRpcProvider, Wallet, isAddress, keccak256, toUtf8Bytes } = require("../../../packages/sdk/node_modules/ethers");

const root = path.resolve(__dirname, "..");
const artifact = (name) => JSON.parse(fs.readFileSync(path.join(root, "build", "contracts", `${name}.json`), "utf8"));
async function deploy(name, signer, args = []) { const source = artifact(name); const contract = await new ContractFactory(source.abi, source.bytecode, signer).deploy(...args); await contract.waitForDeployment(); return contract; }
async function main() {
  const rpc = process.env.SEPOLIA_TESTNET_RPC_URL; const key = process.env.DEPLOYER_PRIVATE_KEY;
  if (!rpc || !key) throw new Error("SEPOLIA_TESTNET_RPC_URL and DEPLOYER_PRIVATE_KEY are required.");
  const provider = new JsonRpcProvider(rpc); const network = await provider.getNetwork(); if (network.chainId !== 11155111n) throw new Error(`Expected Sepolia (11155111), received ${network.chainId}.`);
  const signer = new Wallet(key, provider); const admin = await signer.getAddress();
  const governance = process.env.GOVERNANCE_MULTISIG_ADDRESS || admin;
  if (!isAddress(governance)) throw new Error("GOVERNANCE_MULTISIG_ADDRESS must be a valid Safe/multisig address when configured.");
  const timelock = await deploy("DailyProtocolTimelock", signer, [2 * 24 * 60 * 60, [governance], [governance], admin]);
  const registry = await deploy("DailyRegistry", signer, [admin]);
  const contractRegistry = await deploy("DailyContractRegistry", signer, [admin]);
  const resolver = await deploy("DailyResolver", signer, [await registry.getAddress(), admin]);
  const reverseResolver = await deploy("DailyReverseResolver", signer, [await registry.getAddress()]);
  const mailAnchor = await deploy("DailyMailAnchor", signer, [admin]);
  const registrars = {};
  const registrarRole = keccak256(toUtf8Bytes("REGISTRAR_ROLE"));
  for (const tld of ["dly", "day", "daily"]) { const registrar = await deploy("DailyNameRegistrar", signer, [`Daily ${tld}`, `D${tld.toUpperCase()}`, tld, await registry.getAddress(), keccak256(toUtf8Bytes(tld)), admin, admin]); await (await registry.grantRole(registrarRole, await registrar.getAddress())).wait(); registrars[tld] = await registrar.getAddress(); }
  const bundleCoordinator = await deploy("DailyBundleCoordinator", signer, [admin, registrars.dly, registrars.day, registrars.daily]);
  const bundleOperatorRole = keccak256(toUtf8Bytes("BUNDLE_OPERATOR_ROLE"));
  for (const registrar of Object.values(registrars)) await (await new Contract(registrar, ["function grantRole(bytes32,address)"], signer).grantRole(bundleOperatorRole, await bundleCoordinator.getAddress())).wait();
  const campaignEscrow = await deploy("DailyCampaignEscrow", signer, [admin, admin]);
  const timelockAddress = await timelock.getAddress();
  const rolePairs = [
    [registry, [keccak256(toUtf8Bytes("REGISTRAR_ROLE"))]],
    [resolver, [keccak256(toUtf8Bytes("GATEWAY_MANAGER_ROLE"))]],
    [mailAnchor, [keccak256(toUtf8Bytes("PAUSER_ROLE"))]],
    [campaignEscrow, [keccak256(toUtf8Bytes("POLICY_MANAGER_ROLE")), keccak256(toUtf8Bytes("REWARD_MANAGER_ROLE")), keccak256(toUtf8Bytes("MODERATOR_ROLE"))]],
    ...Object.values(registrars).map(address => [new Contract(address, ["function grantRole(bytes32,address)"], signer), [keccak256(toUtf8Bytes("PRICING_MANAGER_ROLE")), keccak256(toUtf8Bytes("CATALOG_MANAGER_ROLE")), keccak256(toUtf8Bytes("TREASURY_MANAGER_ROLE")), keccak256(toUtf8Bytes("QUOTE_MANAGER_ROLE"))]])
  ];
  for (const [contract, roles] of rolePairs) for (const role of roles) await (await contract.grantRole(role, timelockAddress)).wait();
  const addressEntries = { timelock: await timelock.getAddress(), registry: await registry.getAddress(), resolver: await resolver.getAddress(), reverseResolver: await reverseResolver.getAddress(), mailAnchor: await mailAnchor.getAddress(), bundleCoordinator: await bundleCoordinator.getAddress(), campaignEscrow: await campaignEscrow.getAddress(), ...Object.fromEntries(Object.entries(registrars).map(([tld, address]) => [`registrar.${tld}`, address])) };
  for (const [key, address] of Object.entries(addressEntries)) await (await contractRegistry.setAddress(keccak256(toUtf8Bytes(key)), address)).wait();
  const manifest = { network: "sepolia", chainId: 11155111, deployedAt: new Date().toISOString(), deployer: admin, governanceMultisig: governance, contractRegistry: await contractRegistry.getAddress(), ...addressEntries, registrars };
  const out = path.join(root, "deployments"); fs.mkdirSync(out, { recursive: true }); fs.writeFileSync(path.join(out, "sepolia.json"), JSON.stringify(manifest, null, 2));
  const env = ["# Generated by packages/contracts/scripts/deploy-sepolia.cjs — copy non-secret values into deployment environment.", `SEPOLIA_PROTOCOL_TIMELOCK=${manifest.timelock}`, `SEPOLIA_REGISTRY=${manifest.registry}`, `SEPOLIA_CONTRACT_REGISTRY=${manifest.contractRegistry}`, `SEPOLIA_RESOLVER=${manifest.resolver}`, `SEPOLIA_REVERSE_RESOLVER=${manifest.reverseResolver}`, `SEPOLIA_MAIL_ANCHOR=${manifest.mailAnchor}`, `SEPOLIA_BUNDLE_COORDINATOR=${manifest.bundleCoordinator}`, `SEPOLIA_CAMPAIGN_ESCROW=${manifest.campaignEscrow}`, `SEPOLIA_REGISTRAR_DLY=${manifest.registrars.dly}`, `SEPOLIA_REGISTRAR_DAY=${manifest.registrars.day}`, `SEPOLIA_REGISTRAR_DAILY=${manifest.registrars.daily}`, ""].join("\n"); fs.writeFileSync(path.join(out, "sepolia.generated.env"), env);
  console.log(JSON.stringify({ ...manifest, generatedEnv: path.join(out, "sepolia.generated.env") }, null, 2));
}
main().catch(error => { console.error(error); process.exit(1); });
