import { AbiCoder, BrowserProvider, Contract, JsonRpcProvider, ZeroHash, getBytes, id, type ContractRunner, concat, hexlify, keccak256, randomBytes, solidityPackedKeccak256, toUtf8Bytes, verifyMessage } from "ethers";
import { normalizeLabel, normalizeName } from "./index.js";
import { SEPOLIA_CONTRACTS } from "./sepolia.js";

export type DailyContractAddresses = { registry: string; resolver: string; registrars: { dly: string; day: string; daily: string }; campaignEscrow: string };
let configuredAddresses: DailyContractAddresses = SEPOLIA_CONTRACTS;
/** Applies a deployment manifest at process/app startup; callers need not patch SDK source after a redeployment. */
export function configureDailyContracts(addresses: DailyContractAddresses) { configuredAddresses = addresses; }

const REGISTRAR_ABI = ["function commit(bytes32 commitment)", "function register(string label,address owner,uint64 duration,bytes32 secret) payable", "function renew(bytes32 node,uint64 duration) payable", "function price(uint256 length,uint64 duration) view returns (uint256)", "function expiries(bytes32 node) view returns (uint64)", "function catalog(bytes32 labelhash) view returns (uint8)", "function categoryFor(string label) view returns (uint8)", "function premiumQuotes(bytes32 labelhash) view returns (uint256 registrationAnnualPrice,uint256 renewalAnnualPrice,uint64 expiresAt,bool active)", "function nodeLabelhash(bytes32 node) view returns (bytes32)", "function transferFrom(address from,address to,uint256 tokenId)"];
const REGISTRY_ABI = ["function owner(bytes32 node) view returns (address)", "function resolver(bytes32 node) view returns (address)", "function ttl(bytes32 node) view returns (uint64)", "function setResolver(bytes32 node,address resolver)", "function setTTL(bytes32 node,uint64 ttl)", "function setSubnodeOwner(bytes32 parent,bytes32 labelhash,address owner) returns (bytes32)", "function revokeSubnode(bytes32 parent,bytes32 labelhash) returns (bytes32)"];
const RESOLVER_ABI = ["function addr(bytes32 node,uint256 coinType) view returns (bytes)", "function text(bytes32 node,string key) view returns (string)", "function contenthash(bytes32 node) view returns (bytes)", "function mailKeyHash(bytes32 node) view returns (bytes32)", "function mailKeyVersion(bytes32 node) view returns (uint32)", "function setAddr(bytes32 node,uint256 coinType,bytes value)", "function setText(bytes32 node,string key,string value)", "function setContenthash(bytes32 node,bytes value)", "function setMailKey(bytes32 node,bytes32 hash,uint32 version)"];
const CAMPAIGN_ESCROW_ABI = ["function fund(bytes32 campaignId,uint128 rewardBudget,uint64 deadline) payable", "function platformFeeBps() view returns (uint16)", "function minimumBudget() view returns (uint256)", "function refundUnused(bytes32 campaignId)", "function refundBlocked(bytes32 campaignId)", "function claimReward(bytes32 campaignId,uint256 index,address recipient,uint128 amount,bytes32[] proof)", "function isClaimed(bytes32 campaignId,uint256 index) view returns (bool)", "function rewardRoots(bytes32 campaignId) view returns (bytes32)"];
const BUNDLE_COORDINATOR_ABI = ["function registerBundle(uint8[] tlds,string[] labels,address owner,uint64 duration,bytes32[] secrets,uint256[] values) payable"];
const REVERSE_RESOLVER_ABI = ["function setName(bytes32 node,string name)", "function clearName()", "function name(address account) view returns (string)"];
const MAIL_ANCHOR_ABI = ["function anchor(bytes32 messageHash)", "function anchors(bytes32 messageHash) view returns (address sender,uint64 anchoredAt)"];
const abiCoder = AbiCoder.defaultAbiCoder();

export type NameSearchResult = { name: string; tld: "dly" | "day" | "daily"; node: string; status: "available" | "premium" | "reserved" | "official" | "blocked" | "owned"; priceWei?: bigint; expiresAt?: number };
export type RegistrationIntent = { label: string; tld: "dly" | "day" | "daily"; durationSeconds: bigint; secret: string; commitment: string; priceWei: bigint };
export class DailyContracts {
  readonly provider: JsonRpcProvider | BrowserProvider;
  readonly addresses: DailyContractAddresses;
  constructor(provider: JsonRpcProvider | BrowserProvider = new JsonRpcProvider("https://ethereum-sepolia-rpc.publicnode.com"), addresses: DailyContractAddresses = configuredAddresses) { this.provider = provider; this.addresses = addresses; }
  private registrar(tld: "dly" | "day" | "daily", runner: ContractRunner = this.provider) { return new Contract(this.addresses.registrars[tld], REGISTRAR_ABI, runner); }
  async search(labelInput: string, durationSeconds = 365n * 24n * 60n * 60n): Promise<NameSearchResult[]> {
    const label = normalizeLabel(labelInput); const now = Math.floor(Date.now() / 1000);
    return Promise.all((["dly", "day", "daily"] as const).map(async tld => {
      const name = normalizeName(`${label}.${tld}`); const node = namehashUnchecked(name); const registrar = this.registrar(tld);
      const [exactCategory, expiry, price] = await Promise.all([registrar.catalog(keccak256(toUtf8Bytes(label))), registrar.expiries(node), registrar.price(new TextEncoder().encode(label).length, durationSeconds)]);
      let category = exactCategory; try { category = await registrar.categoryFor(label); } catch { /* Pre-upgrade registrars expose exact catalogue categories only. */ }
      const status = category === 1n ? "premium" : category === 2n ? "reserved" : category === 3n ? "official" : category === 4n ? "blocked" : Number(expiry) > now ? "owned" : "available";
      return { name, tld, node, status, priceWei: BigInt(price), expiresAt: Number(expiry) || undefined };
    }));
  }
  createRegistration(labelInput: string, tld: "dly" | "day" | "daily", owner: string, durationSeconds = 365n * 24n * 60n * 60n): RegistrationIntent {
    const label = normalizeLabel(labelInput); const secret = hexlify(randomBytes(32)); const commitment = solidityPackedKeccak256(["bytes32", "address", "uint64", "bytes32"], [keccak256(toUtf8Bytes(label)), owner, durationSeconds, secret]);
    return { label, tld, durationSeconds, secret, commitment, priceWei: 0n };
  }
  async quoteRegistration(intent: RegistrationIntent): Promise<RegistrationIntent> {
    const registrar = this.registrar(intent.tld); const labelhash = keccak256(toUtf8Bytes(intent.label)); let price = BigInt(await registrar.price(new TextEncoder().encode(intent.label).length, intent.durationSeconds));
    try { const category = BigInt(await registrar.categoryFor(intent.label)); if (category === 1n) { const quote = await registrar.premiumQuotes(labelhash); if (!quote.active || Number(quote.expiresAt) < Math.floor(Date.now() / 1000)) throw new Error("This premium quote is inactive or expired."); price = BigInt(quote.registrationAnnualPrice) * intent.durationSeconds / (365n * 24n * 60n * 60n); } } catch (error) { if (error instanceof Error && error.message.includes("premium quote")) throw error; }
    return { ...intent, priceWei: price };
  }
  async commit(intent: RegistrationIntent, signer: ContractRunner) { return this.registrar(intent.tld, signer).commit(intent.commitment); }
  async estimateCommitFee(intent: RegistrationIntent, signer: ContractRunner) { const gas = await this.registrar(intent.tld, signer).commit.estimateGas(intent.commitment); const feeData = await this.provider.getFeeData(); const price = feeData.maxFeePerGas ?? feeData.gasPrice; if (!price) throw new Error("Network fee data is unavailable."); return { gas: BigInt(gas), feeWei: BigInt(gas) * BigInt(price) }; }
  async register(intent: RegistrationIntent, owner: string, signer: ContractRunner) { return this.registrar(intent.tld, signer).register(intent.label, owner, intent.durationSeconds, intent.secret, { value: intent.priceWei }); }
  async estimateRegistrationFee(intent: RegistrationIntent, owner: string, signer: ContractRunner) { const gas = await this.registrar(intent.tld, signer).register.estimateGas(intent.label, owner, intent.durationSeconds, intent.secret, { value: intent.priceWei }); const feeData = await this.provider.getFeeData(); const price = feeData.maxFeePerGas ?? feeData.gasPrice; if (!price) throw new Error("Network fee data is unavailable."); return { gas: BigInt(gas), feeWei: BigInt(gas) * BigInt(price) }; }
  async resolve(name: string) { const node = namehashUnchecked(normalizeName(name)); const registry = new Contract(this.addresses.registry, REGISTRY_ABI, this.provider); const [owner, resolverAddress] = await Promise.all([registry.owner(node), registry.resolver(node)]); if (resolverAddress === "0x0000000000000000000000000000000000000000") return { node, owner, resolver: undefined, addresses: {} as Record<number, string>, text: {} as Record<string, string>, contenthash: undefined as string | undefined, interfaces: {} as Record<string, boolean> }; const resolver = new Contract(resolverAddress, RESOLVER_ABI, this.provider); const [eth, contenthash, mailKeyHash, mailKeyVersion, interfaces] = await Promise.all([resolver.addr(node, 60), resolver.contenthash(node), resolver.mailKeyHash(node), resolver.mailKeyVersion(node), this.resolverInterfaces(resolverAddress)]); return { node, owner, resolver: resolverAddress, addresses: eth === "0x" ? {} : { 60: eth }, text: {} as Record<string, string>, contenthash: contenthash === "0x" ? undefined : contenthash, mailKeyHash, mailKeyVersion: Number(mailKeyVersion), interfaces };
  }
  async mailboxByNode(node: string) {
    if (!/^0x[a-fA-F0-9]{64}$/.test(node)) throw new Error("Mailbox node must be a bytes32 namehash.");
    const registry = new Contract(this.addresses.registry, REGISTRY_ABI, this.provider);
    const [owner, resolverAddress] = await Promise.all([registry.owner(node), registry.resolver(node)]);
    if (resolverAddress === "0x0000000000000000000000000000000000000000") return { node, owner, resolver: undefined, mailKeyHash: ZeroHash, mailKeyVersion: 0 };
    const resolver = new Contract(resolverAddress, RESOLVER_ABI, this.provider);
    return { node, owner, resolver: resolverAddress, mailKeyHash: await resolver.mailKeyHash(node), mailKeyVersion: Number(await resolver.mailKeyVersion(node)) };
  }
  async publishMailKey(name: string, keyHash: string, version: number, signer: ContractRunner) { const node = namehashUnchecked(normalizeName(name)); const registry = new Contract(this.addresses.registry, REGISTRY_ABI, signer); const current = await registry.resolver(node); if (current.toLowerCase() !== this.addresses.resolver.toLowerCase()) await (await registry.setResolver(node, this.addresses.resolver)).wait(); return new Contract(this.addresses.resolver, RESOLVER_ABI, signer).setMailKey(node, keyHash, version); }
  async setAddress(name: string, coinType: bigint, value: string | Uint8Array, signer: ContractRunner) { const node = namehashUnchecked(normalizeName(name)); return new Contract(this.addresses.resolver, RESOLVER_ABI, signer).setAddr(node, coinType, value); }
  async setText(name: string, key: string, value: string, signer: ContractRunner) { const node = namehashUnchecked(normalizeName(name)); return new Contract(this.addresses.resolver, RESOLVER_ABI, signer).setText(node, key, value); }
  async setContenthash(name: string, value: string, signer: ContractRunner) { const node = namehashUnchecked(normalizeName(name)); return new Contract(this.addresses.resolver, RESOLVER_ABI, signer).setContenthash(node, value); }
  async setTTL(name: string, ttlSeconds: bigint, signer: ContractRunner) { if (ttlSeconds < 0n || ttlSeconds > 31_536_000n) throw new Error("TTL must be from 0 to 31,536,000 seconds."); return new Contract(this.addresses.registry, REGISTRY_ABI, signer).setTTL(namehashUnchecked(normalizeName(name)), ttlSeconds); }
  async ttl(name: string) { return BigInt(await new Contract(this.addresses.registry, REGISTRY_ABI, this.provider).ttl(namehashUnchecked(normalizeName(name)))); }
  async setSubname(parentName: string, label: string, owner: string, signer: ContractRunner) { const parent = namehashUnchecked(normalizeName(parentName)); return new Contract(this.addresses.registry, REGISTRY_ABI, signer).setSubnodeOwner(parent, keccak256(toUtf8Bytes(normalizeLabel(label))), owner); }
  async revokeSubname(parentName: string, label: string, signer: ContractRunner) { const parent = namehashUnchecked(normalizeName(parentName)); return new Contract(this.addresses.registry, REGISTRY_ABI, signer).revokeSubnode(parent, keccak256(toUtf8Bytes(normalizeLabel(label)))); }
  async setSubnameResolver(parentName: string, label: string, resolver: string, signer: ContractRunner) { const parent = namehashUnchecked(normalizeName(parentName)); const node = keccak256(concat([parent, keccak256(toUtf8Bytes(normalizeLabel(label)))])); return new Contract(this.addresses.registry, REGISTRY_ABI, signer).setResolver(node, resolver); }
  async setPrimaryName(reverseResolver: string, name: string, signer: ContractRunner) { if (!/^0x[a-fA-F0-9]{40}$/.test(reverseResolver)) throw new Error("The deployed reverse resolver address is not configured."); return new Contract(reverseResolver, REVERSE_RESOLVER_ABI, signer).setName(namehashUnchecked(normalizeName(name)), normalizeName(name)); }
  async reverseName(reverseResolver: string, account: string) { if (!/^0x[a-fA-F0-9]{40}$/.test(reverseResolver)) return ""; return new Contract(reverseResolver, REVERSE_RESOLVER_ABI, this.provider).name(account); }
  async anchorMailHash(mailAnchor: string, messageHash: string, signer: ContractRunner) { if (!/^0x[a-fA-F0-9]{40}$/.test(mailAnchor) || !/^0x[a-fA-F0-9]{64}$/.test(messageHash)) throw new Error("Mail anchor contract or ciphertext hash is invalid."); return new Contract(mailAnchor, MAIL_ANCHOR_ABI, signer).anchor(messageHash); }
  async resolverInterfaces(address: string) { const supports = new Contract(address, ["function supportsInterface(bytes4) view returns (bool)"], this.provider); const ids = { address: id("addr(bytes32,uint256)").slice(0, 10), text: id("text(bytes32,string)").slice(0, 10), contenthash: id("contenthash(bytes32)").slice(0, 10), mailKey: id("mailKeyHash(bytes32)").slice(0, 10) }; const output: Record<string, boolean> = {}; for (const [key, interfaceId] of Object.entries(ids)) { try { output[key] = Boolean(await supports.supportsInterface(interfaceId)); } catch { output[key] = false; } } return output; }
  /** Resolve an ERC-3668 record directly through a configured Daily gateway and verify its signer before returning bytes. */
  async resolveOffchain(gatewayUrl: string, resolver: string, name: string | Uint8Array, data: string, expectedSigner: string) {
    if (!/^https:\/\//.test(gatewayUrl)) throw new Error("CCIP gateway URL must use HTTPS.");
    if (!/^0x[a-fA-F0-9]{40}$/.test(resolver) || !/^0x[a-fA-F0-9]{40}$/.test(expectedSigner)) throw new Error("Resolver or expected gateway signer is invalid.");
    if (!/^0x[0-9a-fA-F]*$/.test(data)) throw new Error("CCIP resolver calldata must be hex bytes.");
    const nameBytes = typeof name === "string" ? toUtf8Bytes(normalizeName(name)) : name;
    const extraData = abiCoder.encode(["bytes", "bytes"], [nameBytes, data]);
    const response = await fetch(gatewayUrl, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sender: resolver, data: extraData }) });
    if (!response.ok) throw new Error(`CCIP gateway request failed (${response.status}).`);
    const payload = await response.json() as { data?: string; signer?: string };
    if (!payload.data || !/^0x[0-9a-fA-F]*$/.test(payload.data)) throw new Error("CCIP gateway returned an invalid response.");
    const [result, signature] = abiCoder.decode(["bytes", "bytes"], payload.data) as [string, string];
    const digest = solidityPackedKeccak256(["address", "uint256", "bytes", "bytes"], [resolver, BigInt((await this.provider.getNetwork()).chainId), extraData, result]);
    const recovered = verifyMessage(getBytes(digest), signature);
    if (recovered.toLowerCase() !== expectedSigner.toLowerCase()) throw new Error("CCIP gateway signature does not match the configured signer.");
    return { result, response: payload.data, extraData, signer: recovered };
  }
  async renew(name: string, durationSeconds: bigint, signer: ContractRunner) { const normalized = normalizeName(name); const [, tld] = normalized.split("."); const node = namehashUnchecked(normalized); const registrar = this.registrar(tld as "dly" | "day" | "daily"); let annual = BigInt(await registrar.price(new TextEncoder().encode(normalized.split(".")[0]).length, durationSeconds)); try { const labelhash = await registrar.nodeLabelhash(node); const quote = await registrar.premiumQuotes(labelhash); if (quote.active && BigInt(quote.renewalAnnualPrice) > 0n) annual = BigInt(quote.renewalAnnualPrice) * durationSeconds / (365n * 24n * 60n * 60n); } catch { /* Older deployed registrars use the standard price path. */ } return this.registrar(tld as "dly" | "day" | "daily", signer).renew(node, durationSeconds, { value: annual }); }
  async transfer(name: string, from: string, to: string, signer: ContractRunner) { const normalized = normalizeName(name); const [, tld] = normalized.split("."); return this.registrar(tld as "dly" | "day" | "daily", signer).transferFrom(from, to, BigInt(namehashUnchecked(normalized))); }
  async registerBundle(coordinator: string, intents: RegistrationIntent[], owner: string, signer: ContractRunner) { if (!/^0x[a-fA-F0-9]{40}$/.test(coordinator)) throw new Error("The deployed bundle coordinator address is not configured."); if (intents.length < 2 || intents.length > 3) throw new Error("Select two or three available TLDs for a bundle."); const index = { dly: 0, day: 1, daily: 2 } as const; const values = intents.map(intent => intent.priceWei); return new Contract(coordinator, BUNDLE_COORDINATOR_ABI, signer).registerBundle(intents.map(intent => index[intent.tld]), intents.map(intent => intent.label), owner, intents[0].durationSeconds, intents.map(intent => intent.secret), values, { value: values.reduce((sum, value) => sum + value, 0n) }); }
  campaignEscrow(runner: ContractRunner = this.provider) { return new Contract(this.addresses.campaignEscrow, CAMPAIGN_ESCROW_ABI, runner); }
  async fundCampaign(campaignId: string, rewardBudgetWei: bigint, deadline: number, signer: ContractRunner) { const escrow = this.campaignEscrow(signer); const feeBps = BigInt(await escrow.platformFeeBps()); const fee = rewardBudgetWei * feeBps / 10_000n; return escrow.fund(campaignId, rewardBudgetWei, deadline, { value: rewardBudgetWei + fee }); }
  async refundCampaign(campaignId: string, signer: ContractRunner) { if (!/^0x[a-fA-F0-9]{64}$/.test(campaignId)) throw new Error("Campaign ID must be a bytes32 value."); return this.campaignEscrow(signer).refundUnused(campaignId); }
  async refundBlockedCampaign(campaignId: string, signer: ContractRunner) { if (!/^0x[a-fA-F0-9]{64}$/.test(campaignId)) throw new Error("Campaign ID must be a bytes32 value."); return this.campaignEscrow(signer).refundBlocked(campaignId); }
  async claimCampaignReward(input: { campaignId: string; index: bigint; amount: bigint; proof: string[] }, recipient: string, signer: ContractRunner) { if (!/^0x[a-fA-F0-9]{64}$/.test(input.campaignId) || input.index < 0n || input.amount <= 0n || !/^0x[a-fA-F0-9]{40}$/.test(recipient) || !input.proof.every(value => /^0x[a-fA-F0-9]{64}$/.test(value))) throw new Error("Reward claim inputs are invalid."); return this.campaignEscrow(signer).claimReward(input.campaignId, input.index, recipient, input.amount, input.proof); }
}
function namehashUnchecked(name: string): string { let node = "0x" + "00".repeat(32); for (const label of name.split(".").reverse()) node = keccak256(concat([node, keccak256(toUtf8Bytes(label))])); return node; }
