const encoder = new TextEncoder();
const decoder = new TextDecoder();
function encode(bytes) { const view = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes); let value = ""; view.forEach(byte => value += String.fromCharCode(byte)); return btoa(value); }
function decode(value) { const text = atob(value); return Uint8Array.from(text, char => char.charCodeAt(0)); }
async function importPublic(key) { return crypto.subtle.importKey("jwk", key, { name: "ECDH", namedCurve: "P-256" }, true, []); }
async function importPrivate(key) { return crypto.subtle.importKey("jwk", key, { name: "ECDH", namedCurve: "P-256" }, true, ["deriveKey"]); }
export async function generateMailboxKeyPair(version = 1) { const pair = await crypto.subtle.generateKey({ name: "ECDH", namedCurve: "P-256" }, true, ["deriveKey"]); return { publicKey: await crypto.subtle.exportKey("jwk", pair.publicKey), privateKey: await crypto.subtle.exportKey("jwk", pair.privateKey), algorithm: "ECDH-P256", version }; }
export async function publicKeyHash(publicKey) { return `0x${Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", encoder.encode(JSON.stringify(publicKey))))).map(value => value.toString(16).padStart(2, "0")).join("")}`; }
export async function encryptForRecipient(recipientPublicKey, plaintext, version = 1) { const recipient = await importPublic(recipientPublicKey); const ephemeral = await crypto.subtle.generateKey({ name: "ECDH", namedCurve: "P-256" }, true, ["deriveKey"]); const key = await crypto.subtle.deriveKey({ name: "ECDH", public: recipient }, ephemeral.privateKey, { name: "AES-GCM", length: 256 }, false, ["encrypt"]); const iv = crypto.getRandomValues(new Uint8Array(12)); const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, encoder.encode(plaintext)); return { algorithm: "ECDH-P256/AES-256-GCM", version, ephemeralPublicKey: await crypto.subtle.exportKey("jwk", ephemeral.publicKey), iv: encode(iv), ciphertext: encode(ciphertext) }; }
export async function decryptForRecipient(recipientPrivateKey, payload) { const privateKey = await importPrivate(recipientPrivateKey); const ephemeral = await importPublic(payload.ephemeralPublicKey); const key = await crypto.subtle.deriveKey({ name: "ECDH", public: ephemeral }, privateKey, { name: "AES-GCM", length: 256 }, false, ["decrypt"]); const plaintext = await crypto.subtle.decrypt({ name: "AES-GCM", iv: decode(payload.iv) }, key, decode(payload.ciphertext)); return decoder.decode(plaintext); }
export async function encryptVault(value, password) { if (password.length < 12)
    throw new Error("Recovery password must contain at least 12 characters."); const salt = crypto.getRandomValues(new Uint8Array(16)); const iv = crypto.getRandomValues(new Uint8Array(12)); const material = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveKey"]); const iterations = 310_000; const key = await crypto.subtle.deriveKey({ name: "PBKDF2", hash: "SHA-256", salt, iterations }, material, { name: "AES-GCM", length: 256 }, false, ["encrypt"]); const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, encoder.encode(JSON.stringify(value))); return { algorithm: "PBKDF2-SHA256/AES-256-GCM", iterations, salt: encode(salt), iv: encode(iv), ciphertext: encode(ciphertext) }; }
export async function decryptVault(vault, password) { const material = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveKey"]); const key = await crypto.subtle.deriveKey({ name: "PBKDF2", hash: "SHA-256", salt: decode(vault.salt), iterations: vault.iterations }, material, { name: "AES-GCM", length: 256 }, false, ["decrypt"]); const value = await crypto.subtle.decrypt({ name: "AES-GCM", iv: decode(vault.iv) }, key, decode(vault.ciphertext)); return JSON.parse(decoder.decode(value)); }
