import cors from "@fastify/cors";
import jwt from "@fastify/jwt";
import Fastify from "fastify";
import { createHash, randomBytes } from "node:crypto";
import { AbiCoder, Contract, Interface, TypedDataEncoder, Wallet, ZeroHash, getBytes, hashMessage, isAddress, keccak256, solidityPackedKeccak256, toUtf8Bytes, verifyMessage, verifyTypedData } from "ethers";
import { createClient } from "redis";
import { DAILY_NETWORKS, DailyContracts, configureDailyContracts, MAIL_ACKNOWLEDGEMENT_TYPES, MAIL_ENVELOPE_TYPES, SEPOLIA_CONTRACTS, normalizeName } from "@daily/sdk";
import { z } from "zod";
import { loadApiConfig } from "./config.js";
import { DailyPersistence } from "./persistence.js";
import { parseGeographyCsv, quoteAudience, stableMarketingAlias, validateCampaignDraft, validateCampaignPolicy, validateLocationTarget, type CampaignDraft } from "./campaign-domain.js";
import { buildRewardDistribution } from "./campaign-rewards.js";

const config = loadApiConfig();
if (config.contractAddresses) configureDailyContracts(config.contractAddresses);
if (config.contractAddresses) Object.assign(SEPOLIA_CONTRACTS as unknown as Record<string, unknown>, config.contractAddresses);
const app = Fastify({ logger: true, bodyLimit: 11 * 1024 * 1024 });
const contracts = new DailyContracts();
const contractAddresses = config.contractAddresses ?? SEPOLIA_CONTRACTS;
const persistence = new DailyPersistence(config.databaseUrl, config.jwtSecret);
const redis = createClient({ url: config.redisUrl });
redis.on("error", error => app.log.error(error, "Redis client error"));
await redis.connect();
async function purgeExpiredEvidence() { const purged = await persistence.purgeExpiredEvidence(config.evidenceRetentionDays); if (purged) app.log.info({ purged }, "Expired encrypted evidence purged"); }
void purgeExpiredEvidence().catch(error => app.log.error(error, "Initial evidence-retention job failed"));
const evidenceRetentionTimer = setInterval(() => { void purgeExpiredEvidence().catch(error => app.log.error(error, "Evidence-retention job failed")); }, 24 * 60 * 60 * 1000);
evidenceRetentionTimer.unref();
const mailDomain = { name: "Daily Mail", version: "1", chainId: DAILY_NETWORKS.sepolia.chainId, verifyingContract: contractAddresses.registry };
const identityLinkDomain = { name: "Daily Identity Link", version: "1", chainId: DAILY_NETWORKS.sepolia.chainId, verifyingContract: contractAddresses.registry };
const marketingDomain = { name: "Daily Marketing Consent", version: "1", chainId: DAILY_NETWORKS.sepolia.chainId, verifyingContract: contractAddresses.registry };
const MARKETING_CONSENT_TYPES = { MarketingConsent: [{ name: "address", type: "address" }, { name: "country", type: "string" }, { name: "region", type: "string" }, { name: "city", type: "string" }, { name: "categoriesHash", type: "bytes32" }, { name: "deadline", type: "uint256" }] };
const ESCROW_EVENTS = new Interface(["event CampaignFunded(bytes32 indexed campaignId,address indexed marketer,uint256 rewardBudget,uint256 platformFee,uint64 deadline)", "event CampaignBlocked(bytes32 indexed campaignId)", "event RefundClaimed(bytes32 indexed campaignId,uint256 amount)"]);
const PAID_ATTENTION_ENGAGEMENT_TYPES = { PaidAttentionEngagement: [{ name: "recipient", type: "address" }, { name: "messageId", type: "string" }, { name: "action", type: "string" }, { name: "deadline", type: "uint256" }] } as const;
const ESCROW_READ_ABI = ["function minimumBudget() view returns (uint256)", "function platformFeeBps() view returns (uint16)"];
const ERC1271 = new Interface(["function isValidSignature(bytes32 hash,bytes signature) view returns (bytes4)"]);
const abiCoder = AbiCoder.defaultAbiCoder();
const ccipGateway = config.ccipGatewayPrivateKey ? new Wallet(config.ccipGatewayPrivateKey) : undefined;
await app.register(cors, { origin: config.allowedOrigins });
await app.register(jwt, { secret: config.jwtSecret });
app.addHook("onClose", async () => { clearInterval(evidenceRetentionTimer); if (redis.isOpen) await redis.quit(); await persistence.close(); });
async function rateLimit(scope: string, subject: string, maximum: number) {
  const key = `daily:rate:${scope}:${subject.toLowerCase()}:${Math.floor(Date.now() / 60_000)}`; const count = await redis.incr(key); if (count === 1) await redis.expire(key, 60);
  if (count > maximum) { const error = new Error("Rate limit exceeded. Try again in one minute.") as Error & { statusCode: number }; error.statusCode = 429; throw error; }
}
async function validSignature(address: string, digest: string, signature: string, recovered?: string) {
  if (recovered?.toLowerCase() === address.toLowerCase()) return true;
  const code = await contracts.provider.getCode(address);
  if (code === "0x") return false;
  try { return (await contracts.provider.call({ to: address, data: ERC1271.encodeFunctionData("isValidSignature", [digest, signature]) })).slice(0, 10).toLowerCase() === "0x1626ba7e"; } catch { return false; }
}
async function requireProtocolAdmin(actor: string) {
  const registry = new Contract(contractAddresses.registry, ["function hasRole(bytes32,address) view returns (bool)"], contracts.provider);
  if (!await registry.hasRole(ZeroHash, actor)) { const error = new Error("Connected wallet lacks the on-chain Daily protocol-admin role.") as Error & { statusCode: number }; error.statusCode = 403; throw error; }
}
app.get("/health", async (_request, reply) => { try { await Promise.all([persistence.healthcheck(), redis.ping()]); return { ok: true, network: DAILY_NETWORKS.sepolia, contracts: SEPOLIA_CONTRACTS, database: "connected", redis: "connected" }; } catch { return reply.code(503).send({ ok: false, database: "unavailable", redis: "unavailable" }); } });
app.post("/v1/auth/challenge", async (request) => { const { address } = z.object({ address: z.string().refine(isAddress, "Invalid wallet address.") }).parse(request.body); await rateLimit("auth-challenge", address, 10); const value = `Daily Identity login\nNonce: ${randomBytes(16).toString("hex")}`; await persistence.issueNonce(address, value, new Date(Date.now() + 5 * 60_000)); return { message: value }; });
app.post("/v1/auth/verify", async (request, reply) => { const { address, signature } = z.object({ address: z.string().refine(isAddress, "Invalid wallet address."), signature: z.string().min(2) }).parse(request.body); const challenge = await persistence.consumeNonce(address); let recovered: string | undefined; try { recovered = verifyMessage(challenge ?? "", signature); } catch { /* ERC-1271 is checked below. */ } if (!challenge || !await validSignature(address, hashMessage(challenge), signature, recovered)) return reply.code(401).send({ error: "Invalid or expired wallet signature." }); return { token: await reply.jwtSign({ sub: address.toLowerCase() }) }; });
function googleDriveConfig() { if (!config.googleDrive) { const error = new Error("Google Drive is not configured for this environment.") as Error & { statusCode: number }; error.statusCode = 503; throw error; } return config.googleDrive; }
async function googleDriveAccessToken(address: string) { const google = googleDriveConfig(); const refreshToken = await persistence.googleDriveRefreshToken(address); if (!refreshToken) { const error = new Error("Connect Google Drive before storing ciphertext.") as Error & { statusCode: number }; error.statusCode = 409; throw error; } const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: google.clientId, client_secret: google.clientSecret, refresh_token: refreshToken, grant_type: "refresh_token" }) }); if (!response.ok) { const error = new Error("Google Drive access-token refresh failed.") as Error & { statusCode: number }; error.statusCode = 502; throw error; } return (await response.json() as { access_token: string }).access_token; }
app.get("/v1/storage/google-drive/connect", async (request, reply) => { await request.jwtVerify(); const google = googleDriveConfig(); const actor = (request.user as { sub: string }).sub; const state = await reply.jwtSign({ sub: actor, purpose: "google-drive-oauth" }, { expiresIn: "10m" }); const url = new URL("https://accounts.google.com/o/oauth2/v2/auth"); url.search = new URLSearchParams({ client_id: google.clientId, redirect_uri: google.redirectUri, response_type: "code", scope: "https://www.googleapis.com/auth/drive.file openid email", access_type: "offline", prompt: "consent", state }).toString(); return { authorizationUrl: url.toString() }; });
app.get("/v1/storage/google-drive/callback", async (request, reply) => { const params = z.object({ code: z.string().min(1).optional(), state: z.string().min(1), error: z.string().optional() }).parse(request.query); if (params.error) return reply.code(400).type("text/plain").send(`Google Drive authorization failed: ${params.error}`); const google = googleDriveConfig(); let state: { sub: string; purpose?: string }; try { state = await app.jwt.verify(params.state) as { sub: string; purpose?: string }; } catch { return reply.code(400).type("text/plain").send("Google Drive authorization state is invalid or expired."); } if (state.purpose !== "google-drive-oauth" || !params.code) return reply.code(400).type("text/plain").send("Google Drive authorization request is invalid."); const tokenResponse = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ code: params.code, client_id: google.clientId, client_secret: google.clientSecret, redirect_uri: google.redirectUri, grant_type: "authorization_code" }) }); if (!tokenResponse.ok) return reply.code(502).type("text/plain").send("Google Drive token exchange failed."); const tokens = await tokenResponse.json() as { refresh_token?: string; access_token?: string; scope?: string }; if (!tokens.refresh_token) return reply.code(409).type("text/plain").send("Google did not issue a refresh token. Revoke the app in Google Account permissions, then reconnect."); let email: string | undefined; if (tokens.access_token) { const profile = await fetch("https://openidconnect.googleapis.com/v1/userinfo", { headers: { authorization: `Bearer ${tokens.access_token}` } }); if (profile.ok) email = (await profile.json() as { email?: string }).email; } await persistence.saveGoogleDriveConnection(state.sub, tokens.refresh_token, tokens.scope, email); const userUrl = new URL(config.allowedOrigins[0]); userUrl.searchParams.set("storage", "google-drive"); userUrl.searchParams.set("status", "connected"); return reply.redirect(userUrl.toString()); });
app.get("/v1/storage/google-drive", async request => { await request.jwtVerify(); const connection = await persistence.googleDriveConnection((request.user as { sub: string }).sub); return { connector: "google-drive", connected: Boolean(connection && !connection.revoked_at), ...(connection ? { email: connection.email, scope: connection.scope, connectedAt: connection.connected_at } : {}) }; });
app.delete("/v1/storage/google-drive", async request => { await request.jwtVerify(); await persistence.revokeGoogleDriveConnection((request.user as { sub: string }).sub); return { connector: "google-drive", connected: false }; });
app.post("/v1/storage/google-drive/ciphertext", async (request, reply) => { await request.jwtVerify(); const body = z.object({ filename: z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,180}$/), ciphertextBase64: z.string().min(1).max(14_000_000) }).strict().parse(request.body); const actor = (request.user as { sub: string }).sub; const bytes = Buffer.from(body.ciphertextBase64, "base64"); if (!bytes.length || bytes.length > 10 * 1024 * 1024) return reply.code(413).send({ error: "Ciphertext must be between 1 byte and 10 MiB." }); const token = await googleDriveAccessToken(actor); const form = new FormData(); form.append("metadata", new Blob([JSON.stringify({ name: body.filename, mimeType: "application/octet-stream" })], { type: "application/json" })); form.append("file", new Blob([bytes], { type: "application/octet-stream" })); const upload = await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart", { method: "POST", headers: { authorization: `Bearer ${token}` }, body: form }); if (!upload.ok) return reply.code(502).send({ error: "Google Drive ciphertext upload failed." }); const file = await upload.json() as { id: string }; return reply.code(201).send({ id: file.id, filename: body.filename, bytes: bytes.length }); });
app.get("/v1/storage/google-drive/ciphertext/:id", async (request, reply) => { await request.jwtVerify(); const id = (request.params as { id: string }).id; if (!/^[A-Za-z0-9_-]{10,200}$/.test(id)) return reply.code(400).send({ error: "Invalid Google Drive file ID." }); const token = await googleDriveAccessToken((request.user as { sub: string }).sub); const download = await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?alt=media`, { headers: { authorization: `Bearer ${token}` } }); if (!download.ok) return reply.code(502).send({ error: "Google Drive ciphertext download failed." }); reply.header("content-type", "application/octet-stream"); return reply.send(Buffer.from(await download.arrayBuffer())); });
app.get("/v1/names/search/:label", async (request) => ({ results: await contracts.search((request.params as { label: string }).label) }));
app.get("/v1/names/:name", async (request) => ({ name: normalizeName((request.params as { name: string }).name), ...(await contracts.resolve((request.params as { name: string }).name)) }));
app.post("/v1/ccip/records", async (request, reply) => {
  await request.jwtVerify();
  const body = z.object({ name: z.string().min(3).max(255), extraData: z.string().regex(/^0x[0-9a-fA-F]*$/).max(262_146), result: z.string().regex(/^0x[0-9a-fA-F]*$/).max(1_048_578) }).strict().parse(request.body);
  const actor = (request.user as { sub: string }).sub;
  const resolved = await contracts.resolve(body.name);
  if (resolved.owner.toLowerCase() !== actor.toLowerCase()) return reply.code(403).send({ error: "Only the current on-chain name owner may publish this off-chain resolver record." });
  const node = resolved.node;
  const expected = abiCoder.encode(["bytes", "bytes"], [abiCoder.decode(["bytes", "bytes"], body.extraData)[0], abiCoder.decode(["bytes", "bytes"], body.extraData)[1]]);
  if (expected.toLowerCase() !== body.extraData.toLowerCase()) return reply.code(400).send({ error: "CCIP extraData must be canonical abi.encode(bytes name,bytes data)." });
  const requestHash = keccak256(body.extraData);
  await persistence.upsertCcipRecord({ requestHash, node, owner: actor, extraData: body.extraData, result: body.result });
  return reply.code(201).send({ requestHash, node });
});
app.post("/v1/ccip/resolve", async (request, reply) => {
  if (!ccipGateway) return reply.code(503).send({ error: "CCIP gateway signing is not configured." });
  const body = z.object({ sender: z.string().refine(isAddress, "Invalid resolver address."), data: z.string().regex(/^0x[0-9a-fA-F]*$/).max(262_146) }).strict().parse(request.body);
  const record = await persistence.ccipRecord(keccak256(body.data));
  if (!record || record.extra_data.toLowerCase() !== body.data.toLowerCase()) return reply.code(404).send({ error: "No off-chain resolver record exists for this request." });
  const digest = solidityPackedKeccak256(["address", "uint256", "bytes", "bytes"], [body.sender, BigInt(DAILY_NETWORKS.sepolia.chainId), body.data, record.result]);
  const signature = await ccipGateway.signMessage(getBytes(digest));
  return { data: abiCoder.encode(["bytes", "bytes"], [record.result, signature]), signer: ccipGateway.address };
});
app.post("/v1/premium-requests", async (request, reply) => { await request.jwtVerify(); const body = z.object({ name: z.string().min(3).max(128), durationYears: z.number().int().min(1).max(10), reason: z.string().trim().min(10).max(2000), note: z.string().trim().min(1).max(5000), evidenceReference: z.string().uuid().optional() }).strict().parse(request.body); const name = normalizeName(body.name); const [label, tld] = name.split("."); const result = (await contracts.search(label)).find(value => value.tld === tld); if (result?.status !== "premium") return reply.code(409).send({ error: "Only currently catalogued premium names can use this request workflow." }); const actor = (request.user as { sub: string }).sub; await rateLimit("premium-request", actor, 10); return reply.code(201).send(await persistence.createPremiumRequest({ name, applicant: actor, durationYears: body.durationYears, reason: body.reason, note: body.note, evidenceReference: body.evidenceReference })); });
app.get("/v1/premium-requests", async request => { await request.jwtVerify(); return { requests: await persistence.premiumRequests((request.user as { sub: string }).sub) }; });
app.get("/v1/portfolio", async request => {
  await request.jwtVerify(); const address = (request.user as { sub: string }).sub.toLowerCase(); const entries = await persistence.registeredNames();
  const names = (await Promise.all(entries.map(async entry => { if (!entry.name) return undefined; const resolved = await contracts.resolve(entry.name); return resolved.owner.toLowerCase() === address ? { name: entry.name, expiry: entry.expiry ? Number(entry.expiry) : undefined, ...resolved } : undefined; }))).filter(Boolean);
  return { names };
});
const IDENTITY_LINK_TYPES = { IdentityLink: [{ name: "primary", type: "address" }, { name: "linked", type: "address" }, { name: "deadline", type: "uint256" }] } as const;
app.get("/v1/identity-links", async request => { await request.jwtVerify(); return { links: await persistence.identityLinks((request.user as { sub: string }).sub) }; });
app.post("/v1/identity-links/challenge", async (request, reply) => { await request.jwtVerify(); const primary = (request.user as { sub: string }).sub; const { linkedAddress } = z.object({ linkedAddress: z.string().refine(isAddress, "Invalid linked wallet.") }).strict().parse(request.body); if (primary.toLowerCase() === linkedAddress.toLowerCase()) return reply.code(400).send({ error: "A wallet cannot link itself." }); const deadline = Math.floor(Date.now() / 1000) + 15 * 60; return { domain: identityLinkDomain, types: IDENTITY_LINK_TYPES, primary, linked: linkedAddress, deadline }; });
app.post("/v1/identity-links", async (request, reply) => { await request.jwtVerify(); const primary = (request.user as { sub: string }).sub; const body = z.object({ linkedAddress: z.string().refine(isAddress, "Invalid linked wallet."), signature: z.string().min(2), deadline: z.number().int().positive() }).strict().parse(request.body); if (body.deadline < Math.floor(Date.now() / 1000)) return reply.code(400).send({ error: "Identity-link signature has expired." }); if (primary.toLowerCase() === body.linkedAddress.toLowerCase()) return reply.code(400).send({ error: "A wallet cannot link itself." }); const value = { primary, linked: body.linkedAddress, deadline: BigInt(body.deadline) }; let recovered: string | undefined; try { recovered = verifyTypedData(identityLinkDomain, IDENTITY_LINK_TYPES, value, body.signature); } catch { /* ERC-1271 wallets are checked below. */ } if (!await validSignature(body.linkedAddress, TypedDataEncoder.hash(identityLinkDomain, IDENTITY_LINK_TYPES, value), body.signature, recovered)) return reply.code(401).send({ error: "Linked-wallet proof is invalid." }); return persistence.linkIdentity(primary, body.linkedAddress, body.signature, body.deadline); });
app.delete("/v1/identity-links/:address", async (request, reply) => { await request.jwtVerify(); const linked = (request.params as { address: string }).address; if (!isAddress(linked)) return reply.code(400).send({ error: "Invalid linked wallet." }); return persistence.revokeIdentityLink((request.user as { sub: string }).sub, linked); });
app.get("/v1/activity", async request => { await request.jwtVerify(); return { activity: await persistence.activityForWallet((request.user as { sub: string }).sub) }; });
const locationSchema = z.object({ country: z.string().trim().min(2).max(100), region: z.string().trim().min(1).max(100).optional(), city: z.string().trim().min(1).max(100).optional() }).strict();
const categorySchema = z.array(z.string().trim().min(1).max(80)).min(1).max(32).transform(values => [...new Set(values)].sort());
app.post("/v1/marketing/consent", async (request, reply) => {
  await request.jwtVerify(); const body = z.object({ address: z.string().refine(isAddress, "Invalid wallet address."), location: locationSchema, categories: categorySchema, signature: z.string().min(2), deadline: z.number().int().positive() }).parse(request.body); const actor = (request.user as { sub: string }).sub;
  if (actor.toLowerCase() !== body.address.toLowerCase()) return reply.code(403).send({ error: "Consent address must match the authenticated wallet." }); if (body.deadline < Math.floor(Date.now() / 1000)) return reply.code(400).send({ error: "Marketing consent signature has expired." });
  validateLocationTarget(body.location); const value = { address: body.address, country: body.location.country, region: body.location.region ?? "", city: body.location.city ?? "", categoriesHash: keccak256(toUtf8Bytes(JSON.stringify(body.categories))), deadline: BigInt(body.deadline) }; let recovered: string | undefined; try { recovered = verifyTypedData(marketingDomain, MARKETING_CONSENT_TYPES, value, body.signature); } catch { /* Contract wallets are checked below. */ }
  if (!await validSignature(actor, TypedDataEncoder.hash(marketingDomain, MARKETING_CONSENT_TYPES, value), body.signature, recovered)) return reply.code(401).send({ error: "Marketing consent signature is invalid." });
  await persistence.upsertMarketingConsent({ address: actor, ...body.location, categories: body.categories }, body.signature); return reply.code(201).send({ enrolled: true, locationLocked: true, categories: body.categories });
});
app.get("/v1/marketing/consent", async request => { await request.jwtVerify(); const consent = await persistence.consentFor((request.user as { sub: string }).sub); return { consent: consent ?? null }; });
app.get("/v1/marketing/inbox", async request => { await request.jwtVerify(); return { messages: await persistence.paidAttentionInbox((request.user as { sub: string }).sub) }; });
app.get("/v1/marketing/campaigns", async request => { await request.jwtVerify(); return { campaigns: await persistence.campaignsForMarketer((request.user as { sub: string }).sub) }; });
app.post("/v1/marketing/campaigns/:campaignId/refund", async (request, reply) => { await request.jwtVerify(); const actor = (request.user as { sub: string }).sub; const campaignId = (request.params as { campaignId: string }).campaignId; const { transactionHash } = z.object({ transactionHash: z.string().regex(/^0x[a-fA-F0-9]{64}$/) }).strict().parse(request.body); if (!/^0x[a-fA-F0-9]{64}$/.test(campaignId)) return reply.code(400).send({ error: "Invalid campaign ID." }); const receipt = await contracts.provider.getTransactionReceipt(transactionHash); if (!receipt || receipt.status !== 1) return reply.code(409).send({ error: "Refund transaction is missing or unsuccessful." }); const found = receipt.logs.some(log => { if (log.address.toLowerCase() !== SEPOLIA_CONTRACTS.campaignEscrow.toLowerCase()) return false; try { const parsed = ESCROW_EVENTS.parseLog(log); return parsed?.name === "RefundClaimed" && String(parsed.args.campaignId).toLowerCase() === campaignId.toLowerCase(); } catch { return false; } }); if (!found) return reply.code(409).send({ error: "Transaction does not contain the requested refund event." }); return persistence.markCampaignRefunded(campaignId, actor); });
app.post("/v1/marketing/inbox/:id/:action", async (request, reply) => { await request.jwtVerify(); const { id, action } = request.params as { id: string; action: string }; if (!/^[0-9a-f-]{36}$/i.test(id) || !["read", "dismiss"].includes(action)) return reply.code(400).send({ error: "Invalid Paid Attention mailbox action." }); return persistence.updatePaidAttentionMessage(id, (request.user as { sub: string }).sub, action as "read" | "dismiss"); });
app.post("/v1/marketing/inbox/:id/engagement", async (request, reply) => { await request.jwtVerify(); const actor = (request.user as { sub: string }).sub; const id = (request.params as { id: string }).id; if (!/^[0-9a-f-]{36}$/i.test(id)) return reply.code(400).send({ error: "Invalid Paid Attention message ID." }); const body = z.object({ action: z.enum(["acknowledge", "click", "reply"]), signature: z.string().min(2), deadline: z.number().int().positive() }).strict().parse(request.body); if (body.deadline < Math.floor(Date.now() / 1000)) return reply.code(400).send({ error: "Engagement receipt has expired." }); const value = { recipient: actor, messageId: id, action: body.action, deadline: BigInt(body.deadline) }; let recovered: string | undefined; try { recovered = verifyTypedData(mailDomain, PAID_ATTENTION_ENGAGEMENT_TYPES, value, body.signature); } catch { /* ERC-1271 wallets are validated below. */ } if (!await validSignature(actor, TypedDataEncoder.hash(mailDomain, PAID_ATTENTION_ENGAGEMENT_TYPES, value), body.signature, recovered)) return reply.code(401).send({ error: "Paid Attention engagement signature is invalid." }); return persistence.recordCampaignEngagement({ messageId: id, recipient: actor, action: body.action, signature: body.signature, deadline: body.deadline }); });
app.get("/v1/marketing/campaigns/:id/reward-proof", async (request, reply) => { await request.jwtVerify(); const id = (request.params as { id: string }).id; if (!/^[0-9a-f-]{36}$/i.test(id)) return reply.code(400).send({ error: "Invalid campaign ID." }); const proof = await persistence.rewardProof(id, (request.user as { sub: string }).sub); return proof ? { campaignId: proof.chain_campaign_id, root: proof.merkle_root, index: Number(proof.leaf_index), amountWei: proof.amount_wei, proof: proof.merkle_proof } : reply.code(404).send({ error: "No reward claim is available for this wallet." }); });
app.get("/v1/marketing/inbox/:id/reward-proof", async (request, reply) => { await request.jwtVerify(); const id = (request.params as { id: string }).id; if (!/^[0-9a-f-]{36}$/i.test(id)) return reply.code(400).send({ error: "Invalid Paid Attention message ID." }); const proof = await persistence.rewardProofForMessage(id, (request.user as { sub: string }).sub); return proof ? { campaignId: proof.chain_campaign_id, root: proof.merkle_root, index: Number(proof.leaf_index), amountWei: proof.amount_wei, proof: proof.merkle_proof } : reply.code(404).send({ error: "No reward claim is available for this message." }); });
app.post("/v1/marketing/country-changes", async (request, reply) => { await request.jwtVerify(); const body = z.object({ requestedCountry: z.string().trim().min(2).max(100), reason: z.string().trim().min(10).max(2000), evidenceReference: z.string().max(500).optional() }).strict().parse(request.body); const actor = (request.user as { sub: string }).sub; const consent = await persistence.consentFor(actor); if (!consent) return reply.code(409).send({ error: "Enroll in marketing before requesting a country change." }); if (consent.country === body.requestedCountry) return reply.code(400).send({ error: "Requested country is already active." }); await persistence.requestCountryChange(actor, consent.country, body.requestedCountry, body.reason, body.evidenceReference); return reply.code(202).send({ status: "pending" }); });
app.post("/v1/marketing/campaign-quote", async request => { await request.jwtVerify(); const body = z.object({ title: z.string().trim().min(1).max(200), text: z.string().trim().min(1).max(10_000), imageUrl: z.string().url().optional(), clickableUrl: z.string().url(), categories: categorySchema, locations: z.array(locationSchema).min(1).max(100), recipientCount: z.number().int().positive().max(1_000_000) }).strict().parse(request.body); const actor = (request.user as { sub: string }).sub; await rateLimit("campaign-quote", actor, 30); const draft: CampaignDraft = { ...body, locations: body.locations.map(validateLocationTarget) }; validateCampaignDraft(draft); const quote = quoteAudience(draft, await persistence.activeConsents(), await persistence.geographyRates(), await persistence.campaignPolicy()); const escrow = new Contract(contractAddresses.campaignEscrow, ESCROW_READ_ABI, contracts.provider); const [minimumBudget, onChainFeeBps] = await Promise.all([escrow.minimumBudget(), escrow.platformFeeBps()]); if (quote.rewardBudgetWei < BigInt(minimumBudget)) throw new Error(`Quoted reward budget is below the on-chain minimum of ${minimumBudget.toString()} wei.`); if (quote.platformFeeWei !== quote.rewardBudgetWei * BigInt(onChainFeeBps) / 10_000n) throw new Error("Protected API campaign fee policy is not synchronized with the on-chain escrow."); return { eligibleRecipientCount: quote.eligibleAddresses.length, pricePerRecipientWei: quote.pricePerRecipientWei.toString(), rewardBudgetWei: quote.rewardBudgetWei.toString(), platformFeeWei: quote.platformFeeWei.toString(), totalDepositWei: quote.totalDepositWei.toString(), minimumRewardBudgetWei: BigInt(minimumBudget).toString() }; });
app.post("/v1/marketing/campaigns", async (request, reply) => { await request.jwtVerify(); const body = z.object({ campaignId: z.string().regex(/^0x[a-fA-F0-9]{64}$/), escrowTransactionHash: z.string().regex(/^0x[a-fA-F0-9]{64}$/), deadline: z.number().int().positive(), title: z.string().trim().min(1).max(200), text: z.string().trim().min(1).max(10_000), imageUrl: z.string().url().optional(), clickableUrl: z.string().url(), categories: categorySchema, locations: z.array(locationSchema).min(1).max(100), recipientCount: z.number().int().positive().max(1_000_000) }).strict().parse(request.body); const actor = (request.user as { sub: string }).sub; await rateLimit("campaign-create", actor, 10); if (body.deadline <= Math.floor(Date.now() / 1000)) return reply.code(400).send({ error: "Campaign deadline must be in the future." }); const draft: CampaignDraft = { title: body.title, text: body.text, imageUrl: body.imageUrl, clickableUrl: body.clickableUrl, categories: body.categories, locations: body.locations.map(validateLocationTarget), recipientCount: body.recipientCount }; validateCampaignDraft(draft); const quote = quoteAudience(draft, await persistence.activeConsents(), await persistence.geographyRates(), await persistence.campaignPolicy()); const receipt = await contracts.provider.getTransactionReceipt(body.escrowTransactionHash); if (!receipt || receipt.status !== 1) return reply.code(409).send({ error: "Escrow transaction is missing or was not successful." }); let funded: { rewardBudget: bigint; platformFee: bigint; deadline: bigint } | undefined; for (const log of receipt.logs) { if (log.address.toLowerCase() !== SEPOLIA_CONTRACTS.campaignEscrow.toLowerCase()) continue; try { const parsed = ESCROW_EVENTS.parseLog(log); if (parsed?.name === "CampaignFunded" && String(parsed.args.campaignId).toLowerCase() === body.campaignId.toLowerCase() && String(parsed.args.marketer).toLowerCase() === actor.toLowerCase()) funded = { rewardBudget: BigInt(parsed.args.rewardBudget), platformFee: BigInt(parsed.args.platformFee), deadline: BigInt(parsed.args.deadline) }; } catch { /* Ignore logs not emitted by the escrow ABI. */ } }
  if (!funded || funded.rewardBudget !== quote.rewardBudgetWei || funded.platformFee !== quote.platformFeeWei || funded.deadline !== BigInt(body.deadline)) return reply.code(409).send({ error: "Escrow receipt does not match the current aggregate campaign quote." }); try { return reply.code(201).send(await persistence.createFundedCampaign({ chainCampaignId: body.campaignId, marketer: actor, alias: stableMarketingAlias(actor), draft, rewardBudgetWei: funded.rewardBudget, platformFeeWei: funded.platformFee, deadline: body.deadline, transactionHash: body.escrowTransactionHash })); } catch (error) { if (String(error).includes("duplicate")) return reply.code(409).send({ error: "Campaign ID has already been registered." }); throw error; }
});
const policySchema = z.object({ platformFeeBps: z.number().int(), acknowledgementBps: z.number().int(), clickBps: z.number().int(), replyBps: z.number().int(), refundDays: z.number().int(), maxCampaignsPerDay: z.number().int() }).strict();
app.get("/v1/admin/marketing/policy", async request => { await request.jwtVerify(); await requireProtocolAdmin((request.user as { sub: string }).sub); return persistence.campaignPolicy(); });
app.put("/v1/admin/marketing/policy", async request => { await request.jwtVerify(); const actor = (request.user as { sub: string }).sub; await requireProtocolAdmin(actor); const policy = validateCampaignPolicy(policySchema.parse(request.body)); await persistence.setCampaignPolicy(policy); await persistence.audit(actor, "marketing.policy.updated", "marketing_policy", "singleton", policy); return policy; });
app.get("/v1/admin/marketing/geography", async request => { await request.jwtVerify(); await requireProtocolAdmin((request.user as { sub: string }).sub); return { rates: (await persistence.geographyRates()).map(rate => ({ ...rate, pricePerRecipientWei: rate.pricePerRecipientWei.toString() })) }; });
app.post("/v1/admin/marketing/geography/csv", async request => { await request.jwtVerify(); const actor = (request.user as { sub: string }).sub; await requireProtocolAdmin(actor); const csv = z.object({ csv: z.string().min(1).max(1_000_000) }).strict().parse(request.body).csv; const rates = parseGeographyCsv(csv); await persistence.upsertGeographyRates(rates); return { imported: rates.length, rates: rates.map(rate => ({ ...rate, pricePerRecipientWei: rate.pricePerRecipientWei.toString() })) }; });
app.get("/v1/admin/marketing/country-changes", async request => { await request.jwtVerify(); await requireProtocolAdmin((request.user as { sub: string }).sub); return { requests: await persistence.pendingCountryChanges() }; });
app.post("/v1/admin/marketing/country-changes/:id/decision", async request => { await request.jwtVerify(); const actor = (request.user as { sub: string }).sub; await requireProtocolAdmin(actor); const id = (request.params as { id: string }).id; if (!/^[0-9a-f-]{36}$/i.test(id)) { const error = new Error("Invalid country-change request ID.") as Error & { statusCode: number }; error.statusCode = 400; throw error; } const body = z.object({ approved: z.boolean(), reason: z.string().trim().min(3).max(2000) }).strict().parse(request.body); await persistence.decideCountryChange(id, body.approved, actor, body.reason); await persistence.audit(actor, "marketing.country_change.decided", "country_change", id, { approved: body.approved, reason: body.reason }); return { status: body.approved ? "approved" : "rejected" }; });
app.get("/v1/admin/campaigns", async request => { await request.jwtVerify(); await requireProtocolAdmin((request.user as { sub: string }).sub); return { campaigns: await persistence.campaignsForAdmin() }; });
app.get("/v1/admin/premium-requests", async request => { await request.jwtVerify(); await requireProtocolAdmin((request.user as { sub: string }).sub); return { requests: await persistence.premiumRequests() }; });
app.post("/v1/admin/premium-requests/:id/decision", async request => { await request.jwtVerify(); await requireProtocolAdmin((request.user as { sub: string }).sub); const id = (request.params as { id: string }).id; if (!/^[0-9a-f-]{36}$/i.test(id)) { const error = new Error("Invalid premium-request ID.") as Error & { statusCode: number }; error.statusCode = 400; throw error; } const body = z.object({ approved: z.boolean(), registrationWei: z.string().regex(/^\d+$/).optional(), renewalWei: z.string().regex(/^\d+$/).optional(), expiresAt: z.number().int().positive().optional() }).strict().parse(request.body); if (body.approved && (!body.registrationWei || !body.renewalWei || !body.expiresAt || body.expiresAt <= Math.floor(Date.now() / 1000))) { const error = new Error("Approved quotes require positive registration/renewal wei values and a future expiry.") as Error & { statusCode: number }; error.statusCode = 400; throw error; } return persistence.decidePremiumRequest(id, { approved: body.approved, registrationWei: body.registrationWei, renewalWei: body.renewalWei, expiresAt: body.expiresAt ? new Date(body.expiresAt * 1000) : undefined }); });
app.post("/v1/admin/campaigns/:id/block", async (request, reply) => { await request.jwtVerify(); const actor = (request.user as { sub: string }).sub; await requireProtocolAdmin(actor); const id = (request.params as { id: string }).id; const body = z.object({ campaignId: z.string().regex(/^0x[a-fA-F0-9]{64}$/), transactionHash: z.string().regex(/^0x[a-fA-F0-9]{64}$/) }).strict().parse(request.body); const receipt = await contracts.provider.getTransactionReceipt(body.transactionHash); if (!receipt || receipt.status !== 1) return reply.code(409).send({ error: "Campaign-block transaction is missing or unsuccessful." }); let blocked = false; for (const log of receipt.logs) { if (log.address.toLowerCase() !== SEPOLIA_CONTRACTS.campaignEscrow.toLowerCase()) continue; try { const parsed = ESCROW_EVENTS.parseLog(log); if (parsed?.name === "CampaignBlocked" && String(parsed.args.campaignId).toLowerCase() === body.campaignId.toLowerCase()) blocked = true; } catch { /* Ignore unrelated logs. */ } } if (!blocked) return reply.code(409).send({ error: "Transaction does not contain the requested CampaignBlocked event." }); return persistence.markCampaignBlocked(id); });
app.post("/v1/admin/campaigns/:id/review", async (request, reply) => { await request.jwtVerify(); await requireProtocolAdmin((request.user as { sub: string }).sub); const id = (request.params as { id: string }).id; if (!/^[0-9a-f-]{36}$/i.test(id)) return reply.code(400).send({ error: "Invalid campaign ID." }); const { approved } = z.object({ approved: z.boolean() }).strict().parse(request.body); return persistence.decideCampaignReview(id, approved); });
app.post("/v1/admin/campaigns/:id/deliver", async (request, reply) => { await request.jwtVerify(); await requireProtocolAdmin((request.user as { sub: string }).sub); const id = (request.params as { id: string }).id; if (!/^[0-9a-f-]{36}$/i.test(id)) return reply.code(400).send({ error: "Invalid campaign ID." }); const campaigns = await persistence.campaignsForAdmin(); const campaign = campaigns.find(item => item.id === id); if (!campaign || campaign.status !== "approved") return reply.code(409).send({ error: "Only approved, unblocked campaigns may be delivered." }); if (new Date(campaign.deadline).getTime() <= Date.now()) return reply.code(409).send({ error: "Campaign escrow deadline has passed; it cannot be delivered." }); const draft: CampaignDraft = { title: campaign.title, text: campaign.creative.text, imageUrl: campaign.creative.imageUrl, clickableUrl: campaign.creative.clickableUrl, categories: campaign.categories, locations: campaign.locations, recipientCount: campaign.recipient_count }; const quote = quoteAudience(draft, await persistence.activeConsents(), await persistence.geographyRates(), await persistence.campaignPolicy()); if (quote.eligibleAddresses.length > campaign.recipient_count) return reply.code(409).send({ error: "The current eligible audience exceeds the escrowed recipient cap; revise or settle the campaign instead of over-delivering." }); return persistence.deliverCampaign(id, quote.eligibleAddresses); });
app.post("/v1/admin/campaigns/:id/rewards", async (request, reply) => { await request.jwtVerify(); const actor = (request.user as { sub: string }).sub; await requireProtocolAdmin(actor); const id = (request.params as { id: string }).id; if (!/^[0-9a-f-]{36}$/i.test(id)) return reply.code(400).send({ error: "Invalid campaign ID." }); const body = z.object({ allocations: z.array(z.object({ recipient: z.string().refine(isAddress, "Invalid recipient wallet."), amountWei: z.string().regex(/^\d+$/) })).min(1).max(1_000_000) }).strict().parse(request.body); return persistence.storeCampaignRewardDistribution(id, actor, buildRewardDistribution(body.allocations)); });
app.get("/v1/admin/monitoring", async request => { await request.jwtVerify(); await requireProtocolAdmin((request.user as { sub: string }).sub); const started = performance.now(); const [snapshot, ping, latestBlock] = await Promise.all([persistence.monitoringSnapshot(), redis.ping(), contracts.provider.getBlockNumber()]); const rpcLatencyMs = Math.round(performance.now() - started); return { ...snapshot, redis: ping === "PONG" ? "connected" : "unavailable", rpc: { status: "connected", latencyMs: rpcLatencyMs, latestBlock }, relay: { status: await persistence.mailRelayPaused() ? "paused" : "accepting" }, storage: { googleDrive: config.googleDrive ? "configured" : "not-configured" }, network: DAILY_NETWORKS.sepolia }; });
app.get("/v1/admin/reports/operational.csv", async (request, reply) => { await request.jwtVerify(); await requireProtocolAdmin((request.user as { sub: string }).sub); reply.header("content-type", "text/csv; charset=utf-8").header("content-disposition", "attachment; filename=Daily-operational-report.csv"); return persistence.operationalCsv(); });
app.get("/v1/admin/events", async request => { await request.jwtVerify(); await requireProtocolAdmin((request.user as { sub: string }).sub); const query = z.object({ q: z.string().max(120).default(""), limit: z.coerce.number().int().min(1).max(200).default(100) }).parse(request.query); return { events: await persistence.protocolEvents(query.q, query.limit) }; });
app.get("/v1/admin/audit-log", async request => { await request.jwtVerify(); await requireProtocolAdmin((request.user as { sub: string }).sub); const { limit } = z.object({ limit: z.coerce.number().int().min(1).max(200).default(100) }).parse(request.query); return { entries: await persistence.auditEntries(limit) }; });
app.get("/v1/admin/mail/controls", async request => { await request.jwtVerify(); await requireProtocolAdmin((request.user as { sub: string }).sub); return { relayPaused: await persistence.mailRelayPaused() }; });
app.put("/v1/admin/mail/controls", async request => { await request.jwtVerify(); const actor = (request.user as { sub: string }).sub; await requireProtocolAdmin(actor); const { relayPaused } = z.object({ relayPaused: z.boolean() }).strict().parse(request.body); const result = await persistence.setMailRelayPaused(relayPaused, actor); await persistence.audit(actor, "mail.relay_control.updated", "mail_relay", "singleton", { relayPaused }); return result; });
app.get("/v1/admin/mail/moderation", async request => { await request.jwtVerify(); await requireProtocolAdmin((request.user as { sub: string }).sub); const { limit } = z.object({ limit: z.coerce.number().int().min(1).max(200).default(100) }).parse(request.query); const [reports, blocks] = await Promise.all([persistence.spamReports(limit), persistence.senderBlocks(limit)]); return { reports, blocks }; });
async function requireMailboxOwner(node: string, actor: string) { const mailbox = await contracts.mailboxByNode(node); if (mailbox.owner.toLowerCase() !== actor.toLowerCase()) throw new Error("Only the current on-chain mailbox owner may access these encrypted-mail metadata records."); return mailbox; }
const keyHash = (publicKey: Record<string, unknown>) => `0x${createHash("sha256").update(JSON.stringify(publicKey)).digest("hex")}`;
app.post("/v1/mailboxes", async (request, reply) => {
  await request.jwtVerify();
  const body = z.object({ namehash: z.string().regex(/^0x[a-fA-F0-9]{64}$/), publicKey: z.record(z.unknown()).refine(value => value.kty === "EC" && typeof value.x === "string" && typeof value.y === "string", "A P-256 public JWK is required."), keyVersion: z.number().int().positive() }).parse(request.body);
  const mailbox = await requireMailboxOwner(body.namehash, (request.user as { sub: string }).sub);
  if (!mailbox.resolver || mailbox.mailKeyHash === ZeroHash) return reply.code(409).send({ error: "Publish the mailbox key record on-chain before registering its public key." });
  if (mailbox.mailKeyVersion !== body.keyVersion || keyHash(body.publicKey).toLowerCase() !== mailbox.mailKeyHash.toLowerCase()) return reply.code(409).send({ error: "The public key does not match the current on-chain key hash and version." });
  await persistence.registerMailbox(body.namehash, mailbox.owner, mailbox.mailKeyHash, mailbox.mailKeyVersion, body.publicKey);
  return reply.code(201).send({ namehash: body.namehash.toLowerCase(), keyHash: mailbox.mailKeyHash, keyVersion: mailbox.mailKeyVersion });
});
app.get("/v1/mailboxes/:namehash", async (request, reply) => {
  const namehash = (request.params as { namehash: string }).namehash;
  if (!/^0x[a-fA-F0-9]{64}$/.test(namehash)) return reply.code(400).send({ error: "Invalid mailbox namehash." });
  const onChain = await contracts.mailboxByNode(namehash); const record = await persistence.mailboxPublicKey(namehash);
  if (!record || !record.public_key || record.public_key_hash.toLowerCase() !== onChain.mailKeyHash.toLowerCase() || record.key_version !== onChain.mailKeyVersion) return reply.code(404).send({ error: "Recipient has not published an available current public mailbox key." });
  return { namehash: record.namehash, keyHash: record.public_key_hash, keyVersion: record.key_version, publicKey: record.public_key };
});
app.post("/v1/mail/envelopes", async (request, reply) => { await request.jwtVerify(); if (await persistence.mailRelayPaused()) return reply.code(503).send({ error: "Daily Mail relay is temporarily paused." }); const body = z.object({ from: z.string().refine(isAddress, "Invalid sender address."), recipientNamehash: z.string().regex(/^0x[a-fA-F0-9]{64}$/), ciphertext: z.string().min(1).max(5_000_000), signature: z.string().min(2), nonce: z.string().regex(/^\d+$/), deadline: z.number().int().positive() }).parse(request.body); await rateLimit("mail-envelope", body.from, 60); const actor = (request.user as { sub: string }).sub; if (actor.toLowerCase() !== body.from.toLowerCase()) return reply.code(403).send({ error: "Envelope sender must match the authenticated wallet." }); const value = { from: body.from, toNamehash: body.recipientNamehash, ciphertextHash: `0x${(await import("node:crypto")).createHash("sha256").update(body.ciphertext).digest("hex")}`, nonce: BigInt(body.nonce), deadline: BigInt(body.deadline) }; let recovered: string | undefined; try { recovered = verifyTypedData(mailDomain, MAIL_ENVELOPE_TYPES, value, body.signature); } catch { /* ERC-1271 is checked below. */ } if (!await validSignature(actor, TypedDataEncoder.hash(mailDomain, MAIL_ENVELOPE_TYPES, value), body.signature, recovered)) return reply.code(401).send({ error: "Daily Mail EIP-712 envelope signature is invalid." }); const mailbox = await contracts.mailboxByNode(body.recipientNamehash); if (!mailbox.resolver || mailbox.mailKeyHash === ZeroHash) return reply.code(409).send({ error: "Recipient has not activated encrypted Daily Mail." }); return reply.code(202).send(await persistence.submitMail(body, { owner: mailbox.owner, keyHash: mailbox.mailKeyHash, keyVersion: mailbox.mailKeyVersion })); });
app.get("/v1/mail/:namehash", async request => { await request.jwtVerify(); const namehash = (request.params as { namehash: string }).namehash; const { folder } = z.object({ folder: z.enum(["inbox", "archived"]).default("inbox") }).parse(request.query); await requireMailboxOwner(namehash, (request.user as { sub: string }).sub); return { messages: await persistence.listMail(namehash, folder) }; });
app.get("/v1/mail/sent/:address", async (request, reply) => { await request.jwtVerify(); const address = (request.params as { address: string }).address; const actor = (request.user as { sub: string }).sub; if (!isAddress(address) || actor.toLowerCase() !== address.toLowerCase()) return reply.code(403).send({ error: "Sent mail is available only to its authenticated sender." }); return { messages: await persistence.listSentMail(actor) }; });
app.post("/v1/mail/:id/:action", async (request, reply) => { await request.jwtVerify(); const { id, action } = request.params as { id: string; action: string }; const details = await persistence.messageSender(id); if (!details) return reply.code(404).send({ error: "Encrypted-mail metadata was not found." }); const actor = (request.user as { sub: string }).sub; await requireMailboxOwner(details.recipient_namehash, actor); if (action === "block") { await persistence.blockSender(details.recipient_namehash, details.sender_address); return { blocked: details.sender_address }; } if (action === "report") { const reason = z.object({ reason: z.string().max(1000).optional() }).parse(request.body ?? {}).reason; await persistence.reportSpam(id, actor, reason); return { reported: true }; } if (!["read", "acknowledge", "archive", "delete"].includes(action)) return reply.code(400).send({ error: "Unsupported mail action." }); if (action === "acknowledge") { const body = z.object({ signature: z.string().min(2), deadline: z.number().int().positive() }).strict().parse(request.body); if (body.deadline < Math.floor(Date.now() / 1000)) return reply.code(400).send({ error: "Acknowledgement signature has expired." }); const value = { messageId: id, recipientNamehash: details.recipient_namehash, deadline: BigInt(body.deadline) }; let recovered: string | undefined; try { recovered = verifyTypedData(mailDomain, MAIL_ACKNOWLEDGEMENT_TYPES, value, body.signature); } catch { /* Contract wallets are validated through ERC-1271. */ } if (!await validSignature(actor, TypedDataEncoder.hash(mailDomain, MAIL_ACKNOWLEDGEMENT_TYPES, value), body.signature, recovered)) return reply.code(401).send({ error: "Acknowledgement signature is invalid." }); return persistence.updateMail(id, details.recipient_namehash, "acknowledge", body.signature); } return persistence.updateMail(id, details.recipient_namehash, action as "read" | "archive" | "delete"); });
app.post("/v1/evidence", async (request, reply) => { await request.jwtVerify(); const body = z.object({ purpose: z.enum(["premium", "country-change", "brand"]), filename: z.string().trim().min(1).max(180).regex(/^[A-Za-z0-9][A-Za-z0-9._ -]*$/), contentType: z.enum(["application/pdf", "image/png", "image/jpeg"]), ciphertext: z.string().min(1).max(14_000_000) }).strict().parse(request.body); const byteSize = Buffer.byteLength(body.ciphertext, "utf8"); if (byteSize > 10 * 1024 * 1024) return reply.code(413).send({ error: "Encrypted evidence exceeds the 10 MiB ciphertext limit." }); const actor = (request.user as { sub: string }).sub; await rateLimit("evidence-upload", actor, 20); return reply.code(201).send(await persistence.storeEncryptedEvidence({ owner: actor, purpose: body.purpose, filename: body.filename, contentType: body.contentType, byteSize, ciphertext: body.ciphertext })); });
app.get("/v1/evidence/:id", async (request, reply) => { await request.jwtVerify(); const record = await persistence.evidenceForOwner((request.params as { id: string }).id, (request.user as { sub: string }).sub); return record ? { evidence: record } : reply.code(404).send({ error: "Encrypted evidence record was not found." }); });
app.get("/v1/admin/evidence", async request => { await request.jwtVerify(); const actor = (request.user as { sub: string }).sub; await requireProtocolAdmin(actor); const { limit } = z.object({ limit: z.coerce.number().int().min(1).max(200).default(100) }).parse(request.query); const evidence = await persistence.evidenceForAdmin(limit); await persistence.audit(actor, "evidence.metadata.reviewed", "encrypted_evidence", "list", { limit }); return { evidence }; });
app.listen({ host: "0.0.0.0", port: config.port });
